MoviesProject/Controllers/ActorsController.cs
//Veena Harshitha Gandhe
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesProject.Data;
using MoviesProject.Models;

namespace MoviesProject.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ActorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
              return View(await _context.Actors.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Actors == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Gender,NativeLanguage,FilmIndustry,ID,FirstName,LastName,DateOfBirth,ContactNumber,EmailID,StreetAddress,City,State,ZipCode")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }
        [Authorize(Roles ="Administrator")]
        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Actors == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Gender,NativeLanguage,FilmIndustry,ID,FirstName,LastName,DateOfBirth,ContactNumber,EmailID,StreetAddress,City,State,ZipCode")] Actor actor)
        {
            if (id != actor.ID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Actors == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Actors == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Actors'  is null.");
            }
            var actor = await _context.Actors.FindAsync(id);
            if (actor != null)
            {
                _context.Actors.Remove(actor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
          return _context.Actors.Any(e => e.ID == id);
        }
    }
}

MoviesProject/Controllers/CastsController.cs
//Veena Harshitha Gandhe
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesProject.Data;
using MoviesProject.Models;

namespace MoviesProject.Controllers
{
    public class CastsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CastsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Casts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Cast.Include(c => c.Actor).Include(c => c.Movie);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Casts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cast == null)
            {
                return NotFound();
            }

            var cast = await _context.Cast
                .Include(c => c.Actor)
                .Include(c => c.Movie)
                .FirstOrDefaultAsync(m => m.CastID == id);
            if (cast == null)
            {
                return NotFound();
            }

            return View(cast);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Casts/Create
        public IActionResult Create()
        {
            ViewData["ActorID"] = new SelectList(_context.Actors, "ID", "LastName");
            ViewData["MovieID"] = new SelectList(_context.Movies, "MovieID", "Title");
            return View();
        }

        // POST: Casts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CastID,RolePlayed,ActorID,MovieID")] Cast cast)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cast);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActorID"] = new SelectList(_context.Actors, "ID", "Discriminator", cast.ActorID);
            ViewData["MovieID"] = new SelectList(_context.Movies, "MovieID", "MovieID", cast.MovieID);
            return View(cast);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Casts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cast == null)
            {
                return NotFound();
            }

            var cast = await _context.Cast.FindAsync(id);
            if (cast == null)
            {
                return NotFound();
            }
            ViewData["ActorID"] = new SelectList(_context.Actors, "ID", "LastName", cast.ActorID);
            ViewData["MovieID"] = new SelectList(_context.Movies, "MovieID", "Title", cast.MovieID);
            return View(cast);
        }

        // POST: Casts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CastID,RolePlayed,ActorID,MovieID")] Cast cast)
        {
            if (id != cast.CastID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cast);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CastExists(cast.CastID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActorID"] = new SelectList(_context.Actors, "ID", "Discriminator", cast.ActorID);
            ViewData["MovieID"] = new SelectList(_context.Movies, "MovieID", "MovieID", cast.MovieID);
            return View(cast);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Casts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cast == null)
            {
                return NotFound();
            }

            var cast = await _context.Cast
                .Include(c => c.Actor)
                .Include(c => c.Movie)
                .FirstOrDefaultAsync(m => m.CastID == id);
            if (cast == null)
            {
                return NotFound();
            }

            return View(cast);
        }

        // POST: Casts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cast == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Cast'  is null.");
            }
            var cast = await _context.Cast.FindAsync(id);
            if (cast != null)
            {
                _context.Cast.Remove(cast);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CastExists(int id)
        {
          return _context.Cast.Any(e => e.CastID == id);
        }
    }
}

MoviesProject/Controllers/DirectorsController.cs
//Veena Harshitha Gandhe
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesProject.Data;
using MoviesProject.Models;

namespace MoviesProject.Controllers
{
    public class DirectorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DirectorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Directors
        public async Task<IActionResult> Index()
        {
              return View(await _context.Directors.ToListAsync());
        }
        [HttpPost]
        public  IActionResult GetDirectorMovies(int id)
        {
            var director = _context.Directors.Include(m => m.Movies).ThenInclude(e => e.StreamingPlatform)
                                                        .FirstOrDefault(m => m.ID == id);
            return PartialView("_DirectorMovies", director.Movies.ToList());
        }
        // GET: Directors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors
                .Include(m => m.Movies).ThenInclude(s => s.StreamingPlatform)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (director == null)   
            {
                return NotFound();
            }

            return View(director);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Directors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Directors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UniversityAttended,DegreeType,ID,FirstName,LastName,DateOfBirth,ContactNumber,EmailID,StreetAddress,City,State,ZipCode")] Director director)
        {
            if (ModelState.IsValid)
            {
                _context.Add(director);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Directors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors.FindAsync(id);
            if (director == null)
            {
                return NotFound();
            }
            return View(director);
        }

        // POST: Directors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UniversityAttended,DegreeType,ID,FirstName,LastName,DateOfBirth,ContactNumber,EmailID,StreetAddress,City,State,ZipCode")] Director director)
        {
            if (id != director.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(director);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DirectorExists(director.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Directors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (director == null)
            {
                return NotFound();
            }

            return View(director);
        }

        // POST: Directors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Directors == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Directors'  is null.");
            }
            var director = await _context.Directors.FindAsync(id);
            if (director != null)
            {
                _context.Directors.Remove(director);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DirectorExists(int id)
        {
          return _context.Directors.Any(e => e.ID == id);
        }
    }
}

MoviesProject/Views/StreamingPlatforms/Create.cshtml
@*Veena Harshitha Gandhe*@
@model MoviesProject.Models.StreamingPlatform

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container w-25 mt-5 add-new">
    <h2 class="create-text m-4">Add Streaming Platform</h2>
    <div>
    <div class="col-md-4"></div>
        <form asp-action="Create" class="row g-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-12">
                <label asp-for="PlatformName" class="control-label"></label>
                <input asp-for="PlatformName" class="form-control" />
                <span asp-validation-for="PlatformName" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="SubscriptionCost" class="control-label"></label>
                <input asp-for="SubscriptionCost" class="form-control" />
                <span asp-validation-for="SubscriptionCost" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <a asp-action="Index" class="btn">Back to Platforms</a>
            </div>
            <div class="form-group col-md-6 text-end">
                <input type="submit" value="Create" class="btn" />
            </div>
        </form>
        <div class="col-md-4"></div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviesProject/Views/StreamingPlatforms/Delete.cshtml
@*Veena Harshitha Gandhe*@
@model MoviesProject.Models.StreamingPlatform

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container w-50 mt-5 add-new">
    <h2 class="create-text m-4">Delete StreamingPlatform</h2>
    <h3 class="text-center">Are you sure you want to delete this StreamingPlatform?</h3>
    <div class="container w-50 mt-5">
    <dl class="row">
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.PlatformName)
        </dt>
        <dd class = "col-sm-6 text-end">
            @Html.DisplayFor(model => model.PlatformName)
        </dd>
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.SubscriptionCost)
        </dt>
        <dd class = "col-sm-6 text-end">
            @Html.DisplayFor(model => model.SubscriptionCost)
        </dd>
    </dl>

        <form asp-action="Delete" class="row g-3">
        <input type="hidden" asp-for="StreamingPlatformID" />
            <div class="col-md-6">
                <a asp-action="Index" class="btn">Back to Platforms</a>
            </div>
            <div class="col-md-6 text-end">
                <input type="submit" value="Delete" class="btn" />
            </div>
    </form>
</div>
</div>

MoviesProject/Views/StreamingPlatforms/Details.cshtml
@*Veena Harshitha Gandhe*@
@model MoviesProject.Models.StreamingPlatform

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container w-25 mt-5">
    <h2 class="create-text m-4">StreamingPlatform Details</h2>
    <dl class="row">
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.PlatformName)
        </dt>
        <dd class = "col-sm-6 text-end">
            @Html.DisplayFor(model => model.PlatformName)
        </dd>
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.SubscriptionCost)
        </dt>
        <dd class = "col-sm-6 text-end">
            @Html.DisplayFor(model => model.SubscriptionCost)
        </dd>
    </dl>
    <div class="row">
        <div class="col-sm-6">
            <a asp-action="Index" class="btn">Back to Platforms</a>
        </div>
        <div class="col-sm-6 text-end">
            <a asp-action="Edit" class="btn" asp-route-id="@Model?.StreamingPlatformID">Edit</a>
        </div>
    </div>
</div>

MoviesProject/Views/StreamingPlatforms/Edit.cshtml
@*Veena Harshitha Gandhe*@
@model MoviesProject.Models.StreamingPlatform

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container w-25 mt-5 add-new">
    <h2 class="create-text m-4">Edit Streaming Platform</h2>
    <div>
    <div class="col-md-4"></div>
        <form asp-action="Edit" class="row g-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StreamingPlatformID" />
            <div class="form-group col-md-12">
                <label asp-for="PlatformName" class="control-label"></label>
                <input asp-for="PlatformName" class="form-control" />
                <span asp-validation-for="PlatformName" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="SubscriptionCost" class="control-label"></label>
                <input asp-for="SubscriptionCost" class="form-control" />
                <span asp-validation-for="SubscriptionCost" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <a asp-action="Index" class="btn">Back to Platforms</a>
            </div>
            <div class="form-group col-md-6 text-end">
                <input type="submit" value="Save" class="btn" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviesProject/Views/StreamingPlatforms/Index.cshtml
@*Veena Harshitha Gandhe*@
@model IEnumerable<MoviesProject.Models.StreamingPlatform>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container main-content">
    <h1 class="display-4">Streaming Platforms</h1>
</div>
<div class="container mt-1">
    <p class="add-btn">
        <a asp-action="Create" class="btn">Add Streaming Platform</a>
    </p>
    <div>
<table class="table table-bordered table-condensed mb-2">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlatformName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubscriptionCost)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlatformName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SubscriptionCost)
            </td>
            <td>
                <a class="btn" asp-action="Edit" asp-route-id="@item.StreamingPlatformID">Edit</a> |
                <a class="btn" asp-action="Details" asp-route-id="@item.StreamingPlatformID">Details</a> |
                <a class="btn" asp-action="Delete" asp-route-id="@item.StreamingPlatformID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
    <div class="buttons-controller d-flex align-items-center mb-4">
        <div class="m-2">
            <a asp-action="Index" asp-controller="Movies" class="btn">View Movies</a>
        </div>
        <div class="m-2">
            <a asp-action="Index" asp-controller="Actors" class="btn">View Actors</a>
        </div>
        <div class="m-2">
            <a asp-action="Index" asp-controller="Directors" class="btn">View Directors</a>
        </div>
        <div class="m-2">
            <a asp-action="Index" asp-controller="Casts" class="btn">View CastInfo</a>
        </div>
    </div>
</div>