MoviesProject/Controllers/ActorsController.cs
//Veena Harshitha Gandhe
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesProject.Data;
using MoviesProject.Models;

namespace MoviesProject.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ActorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
              return View(await _context.Actors.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Actors == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Gender,NativeLanguage,FilmIndustry,ID,FirstName,LastName,DateOfBirth,ContactNumber,EmailID,StreetAddress,City,State,ZipCode")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }
        [Authorize(Roles ="Administrator")]
        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Actors == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Gender,NativeLanguage,FilmIndustry,ID,FirstName,LastName,DateOfBirth,ContactNumber,EmailID,StreetAddress,City,State,ZipCode")] Actor actor)
        {
            if (id != actor.ID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Actors == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Actors == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Actors'  is null.");
            }
            var actor = await _context.Actors.FindAsync(id);
            if (actor != null)
            {
                _context.Actors.Remove(actor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
          return _context.Actors.Any(e => e.ID == id);
        }
    }
}

MoviesProject/Controllers/DirectorsController.cs
//Veena Harshitha Gandhe
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesProject.Data;
using MoviesProject.Models;

namespace MoviesProject.Controllers
{
    public class DirectorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DirectorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Directors
        public async Task<IActionResult> Index()
        {
              return View(await _context.Directors.ToListAsync());
        }
        [HttpPost]
        public  IActionResult GetDirectorMovies(int id)
        {
            var director = _context.Directors.Include(m => m.Movies).ThenInclude(e => e.StreamingPlatform)
                                                        .FirstOrDefault(m => m.ID == id);
            return PartialView("_DirectorMovies", director.Movies.ToList());
        }
        // GET: Directors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors
                .Include(m => m.Movies).ThenInclude(s => s.StreamingPlatform)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (director == null)   
            {
                return NotFound();
            }

            return View(director);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Directors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Directors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UniversityAttended,DegreeType,ID,FirstName,LastName,DateOfBirth,ContactNumber,EmailID,StreetAddress,City,State,ZipCode")] Director director)
        {
            if (ModelState.IsValid)
            {
                _context.Add(director);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Directors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors.FindAsync(id);
            if (director == null)
            {
                return NotFound();
            }
            return View(director);
        }

        // POST: Directors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UniversityAttended,DegreeType,ID,FirstName,LastName,DateOfBirth,ContactNumber,EmailID,StreetAddress,City,State,ZipCode")] Director director)
        {
            if (id != director.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(director);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DirectorExists(director.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(director);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Directors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Directors == null)
            {
                return NotFound();
            }

            var director = await _context.Directors
                .FirstOrDefaultAsync(m => m.ID == id);
            if (director == null)
            {
                return NotFound();
            }

            return View(director);
        }

        // POST: Directors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Directors == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Directors'  is null.");
            }
            var director = await _context.Directors.FindAsync(id);
            if (director != null)
            {
                _context.Directors.Remove(director);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DirectorExists(int id)
        {
          return _context.Directors.Any(e => e.ID == id);
        }
    }
}

MoviesProject/Controllers/MoviesController.cs
//Veena Harshitha Gandhe
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesProject.Data;
using MoviesProject.Models;

namespace MoviesProject.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MoviesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Movies.Include(m => m.Director).Include(m => m.StreamingPlatform);
            var sessionClicks = HttpContext.Session.Get<List<Movie>>("UserMovieClicks");
            if (sessionClicks != null)
            {
                ViewBag.UserMovieClicks = sessionClicks;
            }
            return View(await applicationDbContext.ToListAsync());
        }
        private void AddClickedMovieToSession(Movie movie)
        {
            var sessionClicks = HttpContext.Session.Get<List<Movie>>("UserMovieClicks");
            if (sessionClicks == null)
            {
                sessionClicks = new List<Movie>();
            }
            var movieInSession = sessionClicks.FirstOrDefault(m => m.MovieID == movie.MovieID);
            if (movieInSession == null)
            {
                sessionClicks.Add(movie);
                HttpContext.Session.Set("UserMovieClicks", sessionClicks);
            }
        }
        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Director)
                .Include(m => m.StreamingPlatform)
                .Include(m => m.Cast).ThenInclude(e => e.Actor)
                .FirstOrDefaultAsync(m => m.MovieID == id);
            if (movie == null)
            {
                return NotFound();
            }
            AddClickedMovieToSession(movie);
            return View(movie);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Movies/Create
        public IActionResult Create()
        {
            ViewData["DirectorID"] = new SelectList(_context.Directors, "ID", "LastName");
            ViewData["StreamingPlatformID"] = new SelectList(_context.StreamingPlatforms, "StreamingPlatformID", "PlatformName");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovieID,Title,ReleaseDate,Genre,DirectorID,StreamingPlatformID")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DirectorID"] = new SelectList(_context.Directors, "ID", "Discriminator", movie.DirectorID);
            ViewData["StreamingPlatformID"] = new SelectList(_context.StreamingPlatforms, "StreamingPlatformID", "StreamingPlatformID", movie.StreamingPlatformID);
            return View(movie);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            ViewData["DirectorID"] = new SelectList(_context.Directors, "ID", "LastName", movie.DirectorID);
            ViewData["StreamingPlatformID"] = new SelectList(_context.StreamingPlatforms, "StreamingPlatformID", "PlatformName", movie.StreamingPlatformID);
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MovieID,Title,ReleaseDate,Genre,DirectorID,StreamingPlatformID")] Movie movie)
        {
            if (id != movie.MovieID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.MovieID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DirectorID"] = new SelectList(_context.Directors, "ID", "Discriminator", movie.DirectorID);
            ViewData["StreamingPlatformID"] = new SelectList(_context.StreamingPlatforms, "StreamingPlatformID", "StreamingPlatformID", movie.StreamingPlatformID);
            return View(movie);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Movies == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Director)
                .Include(m => m.StreamingPlatform)
                .FirstOrDefaultAsync(m => m.MovieID == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Movies == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Movies'  is null.");
            }
            var movie = await _context.Movies.FindAsync(id);
            if (movie != null)
            {
                _context.Movies.Remove(movie);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
          return _context.Movies.Any(e => e.MovieID == id);
        }
    }
}

MoviesProject/Views/Casts/Create.cshtml
@*Veena Harshitha Gandhe*@
@model MoviesProject.Models.Cast

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container w-25 mt-5 add-new">
    <h2 class="create-text m-4">Add Cast</h2>
    <div>
    <div class="col-md-4"></div>
        <form asp-action="Create" class="row g-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-12">
                <label asp-for="ActorID" class="control-label">Actor</label>
                <select asp-for="ActorID" class ="form-control" asp-items="ViewBag.ActorID">
                    <option value="">Select Actor</option>
                </select>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="MovieID" class="control-label">Movie</label>
                <select asp-for="MovieID" class ="form-control" asp-items="ViewBag.MovieID">
                    <option value="">Select Movie</option>
                </select>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="RolePlayed" class="control-label"></label>
                <input asp-for="RolePlayed" class="form-control" />
                <span asp-validation-for="RolePlayed" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <a asp-action="Index" class="btn">Back to CastInfo</a>
            </div>
            <div class="form-group col-md-6 text-end">
                <input type="submit" value="Create" class="btn" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviesProject/Views/Casts/Delete.cshtml
@*Veena Harshitha Gandhe*@
@model MoviesProject.Models.Cast

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container w-50 mt-5 add-new">
<h2 class="create-text m-4">Delete CastInfo</h2>
<h3 class="text-center">Are you sure you want to delete this Cast Info?</h3>
    <div class="container w-50 mt-5">
    <dl class="row">
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.RolePlayed)
        </dt>
        <dd class = "col-sm-6 text-end">
            @Html.DisplayFor(model => model.RolePlayed)
        </dd>
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.Actor)
        </dt>
        <dd class = "col-sm-6 text-end">
            @Html.DisplayFor(model => model.Actor.LastName)
        </dd>
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-6 text-end">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
    </dl>
    
    <form asp-action="Delete" class="row g-3">
        <input type="hidden" asp-for="CastID" />
            <div class="col-md-6">
                <a asp-action="Index" class="btn">Back to CastInfo</a>
                </div>
            <div class="col-md-6 text-end">
                <input type="submit" value="Delete" class="btn" />
            </div>
    </form>
</div>
</div>

MoviesProject/Views/Casts/Details.cshtml
@*Veena Harshitha Gandhe*@
@model MoviesProject.Models.Cast

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container w-25 mt-5">
    <h2 class="create-text m-4">Cast Details</h2>
    <hr />
    <dl class="row">
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.RolePlayed)
        </dt>
        <dd class="col-sm-6 text-end">
            @Html.DisplayFor(model => model.RolePlayed)
        </dd>
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.Actor)
        </dt>
        <dd class="col-sm-6 text-end">
            @Html.DisplayFor(model => model.Actor.LastName)
        </dd>
        <dt class = "col-sm-6">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class="col-sm-6 text-end">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
    </dl>
    <div class="row">
        <div class="col-sm-6">
            <a asp-action="Index" class="btn">Back to CastInfo</a>
        </div>
        <div class="col-sm-6 text-end">
            <a asp-action="Edit" class="btn" asp-route-id="@Model?.CastID">Edit</a>
        </div>
    </div>
</div>

MoviesProject/Views/Casts/Edit.cshtml
@*Veena Harshitha Gandhe*@
@model MoviesProject.Models.Cast

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container w-50 mt-5 add-new">
    <h2 class="create-text m-4">Edit Cast</h2>
    <div>
    <div class="col-md-4"></div>
        <form asp-action="Edit" class="row g-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CastID" />
            <div class="form-group col-md-12">
                <label asp-for="RolePlayed" class="control-label"></label>
                <input asp-for="RolePlayed" class="form-control" />
                <span asp-validation-for="RolePlayed" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="ActorID" class="control-label">Actor</label>
                <select asp-for="ActorID" class="form-control" asp-items="ViewBag.ActorID"></select>
                <span asp-validation-for="ActorID" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="MovieID" class="control-label">Movie</label>
                <select asp-for="MovieID" class="form-control" asp-items="ViewBag.MovieID"></select>
                <span asp-validation-for="MovieID" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <a asp-action="Index" class="btn">Back to CastInfo</a>
            </div>
            <div class="form-group col-md-6 text-end">
                <input type="submit" value="Save" class="btn" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviesProject/Views/Casts/Index.cshtml
@*Veena Harshitha Gandhe*@
@model IEnumerable<MoviesProject.Models.Cast>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container main-content">
    <h1 class="display-4">Cast</h1>
</div>
<div class="container mt-1">
    <p class="add-btn">
        <a asp-action="Create" class="btn">Add Cast</a>
    </p>
    <div>
        <table class="table table-bordered table-condensed mb-2">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Actor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RolePlayed)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Actor.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RolePlayed)
            </td>
            <td>
                <a class="btn" asp-action="Edit" asp-route-id="@item.CastID">Edit</a> |
                <a class="btn" asp-action="Details" asp-route-id="@item.CastID">Details</a> |
                <a class="btn" asp-action="Delete" asp-route-id="@item.CastID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
 </div>
    <div class="buttons-controller d-flex align-items-center mb-4">
        <div class="m-2">
            <a asp-action="Index" asp-controller="Actors" class="btn">View Actors</a>
        </div>
        <div class="m-2">
            <a asp-action="Index" asp-controller="Directors" class="btn">View Directors</a>
        </div>
        <div class="m-2">
            <a asp-action="Index" asp-controller="Movies" class="btn">View Movies</a>
        </div>
        <div class="m-2">
            <a asp-action="Index" asp-controller="StreamingPlatforms" class="btn">View StreamingPlatforms</a>
        </div>
    </div>
</div>